[iOS] Feature 3. 이슈 상세 페이지 하단 시트 추가
boostcamp-2020/IssueTracker-09 pull request #135
Opened 2020-11-05 13:47 UTC by Seungeon-Kim

## 작업 내용

- 마일스톤 목록 페이지 레이아웃 수정
- 이슈 상세 페이지 레이아웃 수정 
- 이슈 상세 페이지 하단 시트 추가

## 기타 사항

- 하단 시트 내 이벤트 처리는 아직 안되있음.
- 등록된 이슈가 없어서 현재 확인이 안됨. (디비에 더미 데이터를 추가해야할 것 같음)

2020-11-05 13:49 UTC, Seungeon-Kim commented
늦어서 죄송해요~ 낼 오전에 확인하고 이상없으면 머지 후 마스터 브랜치에 프리징 부탁드리겠습니다! ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2020-11-05 14:05 UTC, KYHyeon requested changes

2020-11-05 14:05 UTC, KYHyeon commented on iOS/IssueTracker/IssueTracker/ViewControllers/Milestone/MilestoneCacheService.swift
> -            self?.milestones = (try? result.get().milestones) ?? []
서버에서 데이터를 가져오는 부분인데 왜 지우고 더미 데이터를 넣으셨을까요..?

2020-11-05 14:25 UTC, KYHyeon approved these changes

2020-11-05 14:26 UTC, merged

2020-11-05 14:27 UTC, KYHyeon commented on iOS/IssueTracker/IssueTracker/ViewControllers/Milestone/MilestoneCacheService.swift
> -            self?.milestones = (try? result.get().milestones) ?? []
더미 데이터를 넣는 부분인것 같은데 일단 수정해놓겠습니다.

2020-11-06 04:44 UTC, Seungeon-Kim commented on iOS/IssueTracker/IssueTracker/ViewControllers/Milestone/MilestoneCacheService.swift
> -            self?.milestones = (try? result.get().milestones) ?? []
마일스톤 여러개일때 레이아웃을 좀 보고싶어서 더미를 넣었었어요 😂